# Generated by Django 5.2.7 on 2025-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_potholedetection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholedetection',
            name='deviceId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
