# Generated by Django 5.2.7 on 2025-10-13 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_potholedetection_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='potholedetection',
            name='share_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
